import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'
import tailwindcss from "tailwindcss";

// https://vitejs.dev/config/
export default defineConfig({
  css: {
    postcss: {
      plugins: [tailwindcss()],
    },
  },
  plugins: [react()],
  base: '/',
  optimizeDeps: {
    // Vite's dep optimizer can split MUI v5's lazy-initialized modules across
    // shared chunks leaving `styled` undefined at runtime ("styled_default is
    // not a function"), and the chunk layout is non-deterministic across runs.
    // noDiscovery + an explicit, complete include list makes the pre-bundle
    // fully deterministic so the app starts clean every time. If you add a new
    // dependency, add it to the include list below.
    noDiscovery: true,
    include: [
      'js-cookie',
      'react/jsx-dev-runtime',
      'react/jsx-runtime',
      '@mui/material',
      '@mui/material/Avatar',
      '@mui/material/Badge',
      '@mui/material/Box',
      '@mui/material/Button',
      '@mui/material/Stack',
      '@mui/material/Switch',
      '@mui/material/TextField',
      '@mui/material/Tooltip',
      '@mui/material/styles',
      '@mui/icons-material',
      '@mui/icons-material/AccountBox',
      '@mui/icons-material/AddComment',
      '@mui/icons-material/AdminPanelSettings',
      '@mui/icons-material/ArrowDropDown',
      '@mui/icons-material/Check',
      '@mui/icons-material/CheckCircleOutlined',
      '@mui/icons-material/ChevronLeft',
      '@mui/icons-material/ChevronRight',
      '@mui/icons-material/Circle',
      '@mui/icons-material/Close',
      '@mui/icons-material/Collections',
      '@mui/icons-material/DarkMode',
      '@mui/icons-material/DashboardCustomize',
      '@mui/icons-material/Delete',
      '@mui/icons-material/Download',
      '@mui/icons-material/Edit',
      '@mui/icons-material/ErrorOutlined',
      '@mui/icons-material/Feed',
      '@mui/icons-material/Home',
      '@mui/icons-material/HowToReg',
      '@mui/icons-material/Hub',
      '@mui/icons-material/LocationOn',
      '@mui/icons-material/LockReset',
      '@mui/icons-material/Logout',
      '@mui/icons-material/ManageAccounts',
      '@mui/icons-material/Menu',
      '@mui/icons-material/MoreHoriz',
      '@mui/icons-material/Notifications',
      '@mui/icons-material/OpenInNew',
      '@mui/icons-material/Report',
      '@mui/icons-material/RestartAlt',
      '@mui/icons-material/Search',
      '@mui/icons-material/Send',
      '@mui/icons-material/Settings',
      '@mui/icons-material/Share',
      '@mui/icons-material/Tag',
      '@mui/icons-material/ThreeP',
      '@mui/icons-material/ThumbDown',
      '@mui/icons-material/ThumbUp',
      '@mui/icons-material/TrendingUp',
      '@mui/icons-material/Visibility',
      '@mui/icons-material/VisibilityOff',
      '@mui/icons-material/ZoomIn',
      '@mui/icons-material/ZoomOut',
      'axios',
      'date-fns',
      'date-fns/locale',
      'prop-types',
      'react',
      'react-dom',
      'react-dom/client',
      'react-helmet',
      'react-redux',
      'react-router',
      'react-router-dom',
      'redux',
      'redux-persist',
      'redux-persist/integration/react',
      'redux-persist/lib/storage',
      'socket.io-client',
    ],
  },
})
